server:
  port: "8080"
  maxHeaderBytes: 1048576 # 1MB
  readTimeout: 10s
  writeTimeout: 10s

db:
  host: "db"
  port: "5432"
  username: "postgres"
  dbname: "chat"
  sslmode: "disable"
